# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lumo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lumo
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseAuth'
  pod 'FirebaseMessaging'

  target 'LumoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LumoUITests' do
    # Pods for testing
  end

end
  
